const BASE_BACKEND_URL = 'http://127.0.0.1:8000/';
const BASE_BACKEND_API_URL = BASE_BACKEND_URL + 'api/';
const CATEGORY_IMAGE_URL = BASE_BACKEND_URL + 'images/categories/'

export {
    BASE_BACKEND_URL,
    BASE_BACKEND_API_URL,
    CATEGORY_IMAGE_URL,
}